name: gg_is_flutter
description: Detects if a directory contains a dart or flutter project or something else.
version: 1.0.0
repository: https://github.com/inlavigo/gg_is_flutter.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^1.0.8
  gg_process: ^1.0.7
  gg_project_root: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  gg_capture_print: ^1.0.3
  gg_check: ^1.0.2
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
